channels:
  - conda-forge
dependencies:
  - python >=3.9,<3.11
  - numpy >=1.24.1
  - pip >=22.3.1
  - statista >=0.1.8
  - pyramids >=0.3.2
  - loguru >=0.6.0
  - pytest >=7.2.1
  - pytest-cov >=4.0.0
