name: Linux
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
  Run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest]
        python-version: ["3.9", "3.10", "3.11"]
    env:
      OS: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install GDAL
        run: |
            python -m pip install --upgrade pip
            pip install --no-cache-dir Cython
            pip install --find-links=https://girder.github.io/large_image_wheels --no-cache GDAL

      - name: Test GDAL installation
        run: |
            python -c "from osgeo import gdal"
            gdalinfo --version

      - name: Install dependencies
        run: |
            pip install -r requirements.txt -r requirements-dev.txt
            python setup.py install

      - name: Generate coverage report
        run: |
          python -m pytest -vvv --cov=geostatista --cov-report=xml

      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3
